routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('checkout/notification', ['as' => 'checkout.notification','uses' => 'Frontend\CheckoutController@checkoutNotification']);


Route::get('/', ['as' => 'index','uses' => 'Frontend\IndexController@index']);
Route::get('/contato', ['as' => 'contato','uses' => 'Frontend\IndexController@contato']);

Route::get('login', ['as' => 'login','uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'postlogin','uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'logout','uses' => 'Auth\LoginController@logout']);
Route::get('register', ['as'=>'register','uses'=>'Auth\RegisterController@showregister']);
Route::post('register', ['as'=>'postregister','uses' => 'Auth\RegisterController@register']);
if (setting('forgot_password')){
    Route::get('password/remind', ['as'=>'password.remind','uses'=>'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/remind', ['as'=>'send.password.remind','uses'=>'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset/{token}', ['as'=>'password.reset', 'uses'=>'Auth\ResetPasswordController@showResetForm']);
    Route::post('password/reset', ['as'=>'password.update','uses'=>'Auth\ResetPasswordController@reset']);
}

Route::group(['middleware' => 'auth'], function() {
    Route::get('recurso', ['as' => 'recurso.index','uses' => 'Frontend\RecursosController@create']);
    Route::post('recurso', ['as' => 'recurso.store','uses' => 'Frontend\RecursosController@store']);
    Route::get('recurso/{id}/pagar', ['as' => 'recurso.pagar','uses' => 'Frontend\RecursosController@pagar']);
    Route::post('recurso/{id}/pagar', ['as' => 'recurso.pagar.post','uses' => 'Frontend\RecursosController@pagarpost']);

    Route::get('minha-conta', ['as' => 'minhaconta.index','uses' => 'Frontend\MinhaContaController@index']);
    Route::get('minha-conta/recurso/{id}/editar', ['as' => 'minhaconta.recurso.edit','uses' => 'Frontend\MinhaContaController@edit']);
    Route::post('minha-conta/recurso/{id}/editar', ['as' => 'minhaconta.recurso.update','uses' => 'Frontend\MinhaContaController@update']);
    Route::post('minha-conta/recurso/{id}/editar/imagem', ['as' => 'minhaconta.recurso.update.image','uses' => 'Frontend\MinhaContaController@updateImage']);
    Route::get('minha-conta/configuracoes', ['as' => 'minhaconta.settings','uses' => 'Frontend\MinhaContaController@settings']);
    Route::post('minha-conta/configuracoes/editar', ['as' => 'minhaconta.settings.update.details','uses' => 'Frontend\MinhaContaController@settingsupdate']);
    Route::post('minha-conta/configuracoes/editar/senha', ['as' => 'minhaconta.settings.update.password','uses' => 'Frontend\MinhaContaController@settingsupdatepassword']);
    Route::get('minha-conta/recurso/{id}/download', ['as' => 'minhaconta.recurso.download','uses' => 'Frontend\MinhaContaController@download']);

    Route::get('checkout/success', ['as' => 'checkout.sucess','uses' => 'Frontend\RecursosController@checkoutSuccess']);
});



Route::group(['middleware' => ['auth','role:Administrador|Funcionário'],'prefix' => 'dashboard', 'as' => 'dashboard.'], function() {
    Route::get('/', ['as' => 'index','uses' => 'Dashboard\DashboardController@index']);

    Route::get('profile', ['as' => 'profile','uses' => 'Dashboard\ProfileController@index']);
    Route::post('profile/details/update', ['as' => 'profile.update.details','uses' => 'Dashboard\ProfileController@updateDetails']);
    Route::post('profile/login-details/update', ['as' => 'profile.update.login-details','uses' => 'Dashboard\ProfileController@updateLoginDetails']);

    Route::get('user', ['as' => 'user.list','uses' => 'Dashboard\UsersController@index']);
    Route::get('user/create', ['as' => 'user.create','uses' => 'Dashboard\UsersController@create']);
    Route::post('user/create', ['as' => 'user.store','uses' => 'Dashboard\UsersController@store']);
    Route::get('user/{user_id}/edit', ['as' => 'user.edit','uses' => 'Dashboard\UsersController@edit']);
    Route::post('user/{user_id}/update/details', ['as' => 'user.update.details','uses' => 'Dashboard\UsersController@updateDetails']);
    Route::post('user/{user_id}/update/login-details', ['as' => 'user.update.login-details','uses' => 'Dashboard\UsersController@updateLoginDetails']);      //----------testar
    Route::post('user/{user_id}/update/role', ['as' => 'user.update.role','uses' => 'Dashboard\UsersController@updateRole']);
    Route::post('user/{user_id}/update/permissions', ['as' => 'user.update.permission','uses' => 'Dashboard\UsersController@updatePermissions']);
    Route::delete('user/{user_id}/delete', ['as' => 'user.delete','uses' => 'Dashboard\UsersController@destroy']);

    Route::get('arquivo/download/{id}', ['as' => 'arquivo.download','uses' => 'Dashboard\ArquivosController@download']);

    Route::get('recurso', ['as' => 'recurso.list','uses' => 'Dashboard\RecursosController@index']);
    Route::get('recurso/{recurso_id}/edit', ['as' => 'recurso.edit','uses' => 'Dashboard\RecursosController@edit']);
    Route::post('recurso/{recurso_id}/update', ['as' => 'recurso.update','uses' => 'Dashboard\RecursosController@update']);
    Route::post('recurso/{recurso_id}/update/status', ['as' => 'recurso.update.recursofile','uses' => 'Dashboard\RecursosController@updateRecursoFile']);
    Route::post('recurso/{recurso_id}/update/pagamento', ['as' => 'recurso.update.pagamento','uses' => 'Dashboard\RecursosController@updatePagamento']);
    Route::get('recurso/{recurso_id}/view', ['as' => 'recurso.show','uses' => 'Dashboard\RecursosController@show']);
    Route::delete('recurso/{recurso_id}/delete', ['as' => 'recurso.delete','uses' => 'Dashboard\RecursosController@destroy']);

    Route::get('categoria', ['as' => 'categoria.list','uses' => 'Dashboard\CategoriasController@index']);
    Route::get('categoria/create', ['as' => 'categoria.create','uses' => 'Dashboard\CategoriasController@create']);
    Route::post('categoria/store', ['as' => 'categoria.store','uses' => 'Dashboard\CategoriasController@store']);
    Route::get('categoria/{id}/edit', ['as' => 'categoria.edit','uses' => 'Dashboard\CategoriasController@edit']);
    Route::post('categoria/{id}/update', ['as' => 'categoria.update','uses' => 'Dashboard\CategoriasController@update']);
    Route::delete('categoria/{id}/delete', ['as' => 'categoria.destroy','uses' => 'Dashboard\CategoriasController@destroy']);


    Route::get('infracao', ['as' => 'tipomulta.list','uses' => 'Dashboard\TipoMultasController@index']);
    Route::get('infracao/create', ['as' => 'tipomulta.create','uses' => 'Dashboard\TipoMultasController@create']);
    Route::post('infracao/store', ['as' => 'tipomulta.store','uses' => 'Dashboard\TipoMultasController@store']);
    Route::get('infracao/{id}/edit', ['as' => 'tipomulta.edit','uses' => 'Dashboard\TipoMultasController@edit']);
    Route::post('infracao/{id}/update', ['as' => 'tipomulta.update','uses' => 'Dashboard\TipoMultasController@update']);
    Route::delete('infracao/{id}/delete', ['as' => 'tipomulta.destroy','uses' => 'Dashboard\TipoMultasController@destroy']);


    Route::get('role', ['as' => 'role.index','uses' => 'Dashboard\RolesController@index']);
    Route::get('role/create', ['as' => 'role.create','uses' => 'Dashboard\RolesController@create']);
    Route::post('role/store', ['as' => 'role.store','uses' => 'Dashboard\RolesController@store']);
    Route::get('role/{role_id}/edit', ['as' => 'role.edit','uses' => 'Dashboard\RolesController@edit']);
    Route::post('role/{role_id}/update', ['as' => 'role.update','uses' => 'Dashboard\RolesController@update']);
    Route::delete('role/{role_id}/delete', ['as' => 'role.delete','uses' => 'Dashboard\RolesController@destroy']);

    Route::get('permission', ['as' => 'permission.index','uses' => 'Dashboard\PermissionsController@index']);
    Route::get('permission/create', ['as' => 'permission.create','uses' => 'Dashboard\PermissionsController@create']);
    Route::post('permission/store', ['as' => 'permission.store','uses' => 'Dashboard\PermissionsController@store']);
    Route::get('permission/{permission_id}/edit', ['as' => 'permission.edit','uses' => 'Dashboard\PermissionsController@edit']);
    Route::post('permission/{permission_id}/update', ['as' => 'permission.update','uses' => 'Dashboard\PermissionsController@update']);
    Route::delete('permission/{permission_id}/delete', ['as' => 'permission.destroy','uses' => 'Dashboard\PermissionsController@destroy']);

    Route::get('settings', ['as' => 'settings.general','uses' => 'Dashboard\SettingsController@general']);
    Route::post('settings/general', ['as' => 'settings.general.update','uses' => 'Dashboard\SettingsController@updategeneral']);
    Route::get('settings/auth', ['as' => 'settings.auth','uses' => 'Dashboard\SettingsController@auth']);
    Route::post('settings/auth', ['as' => 'settings.auth.update','uses' => 'Dashboard\SettingsController@updateauth']);
});

app/Http/Controllers/Dashboard/ArquivosController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Arquivo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class ArquivosController extends Controller
{
    public function download($id)
    {
        $arquivo = Arquivo::find($id);

        return Storage::download($arquivo->path);
    }

    public function delete($id)
    {
        $arquivo = Arquivo::find($id);
        $recurso_id = $arquivo->recurso_id;

        Storage::delete($arquivo->path);

        return redirect()->route('dashboard.recurso.edit',$recurso_id)->withSuccess('Arquivo excluido com sucesso!');
    }
}

app/Http/Controllers/Dashboard/CategoriasController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\Categoria\CreateCategoriaRequest;
use App\Http\Requests\Dashboard\Categoria\UpdateCategoriaRequest;
use App\Models\Categoria;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;

class CategoriasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Auth::user()->can('Visualizar categoria')){
            return redirect()->back();
        }
        $peer_page = 15;
        $search = Input::get('search');
        $categorias = Categoria::Query();
        if ($search <> "") {
            $categorias->where(function ($q) use ($search) {
                $q->where('nome', "like", "%{$search}%");
            });
        }
        $categorias = $categorias->paginate($peer_page);
        if ($search) {
            $categorias->appends(['search' => $search]);
        }

        return view('dashboard.categoria.list', compact('categorias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::user()->can('Criar categoria')){
            return redirect()->back();
        }

        return view('dashboard.categoria.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoriaRequest $request)
    {
        if(!Auth::user()->can('Criar categoria')){
            return redirect()->route('dashboard.categoria.list')->withErrors('Você não esta autorizado para executar esta ação.');
        }

        $categoria = new Categoria();
        $categoria->nome = $request->nome;
        $categoria->preco = $request->preco;
        $categoria->save();

        return redirect()->route('dashboard.categoria.list')->withSuccess('Categoria criada com sucesso!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $$tipomulta_id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!Auth::user()->can('Editar categoria')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }
        $edit = true;
        $categoria = Categoria::find($id);

        return view('dashboard.categoria.edit',compact('edit', 'categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoriaRequest $request, $id)
    {
        if(!Auth::user()->can('Editar categoria')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }

        $categoria = Categoria::find($id);
        $categoria->nome = $request->nome;
        $categoria->preco = $request->preco;
        $categoria->save();

        return redirect()->back()->withSuccess('Categoria atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!Auth::user()->can('Excluir categoria')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }
        $categoria = Categoria::find($id);
        $categoria->delete();

        return redirect()->route('dashboard.categoria.list')->withSuccess('Categoria excluída com sucesso!');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Recurso;
use App\Models\User;
use Carbon\Carbon;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $recursos = Recurso::all();

        $monthsarray[] = date('m/Y');
        for ($i = 1; $i < 6; $i++) {
            $monthsarray[] = date('m/Y', strtotime("-$i month"));
        }
        $months='';
        foreach ($monthsarray as $m){
            $months="'".$m."'".",".$months;
        }

        $result = Recurso::select('id', 'created_at')
            ->where("created_at",">", Carbon::now()->subMonths(6))
            ->get()
            ->groupBy(function($date) {
                return Carbon::parse($date->created_at)->format('m');
            });
        $resultarray = [];
        foreach ($result as $r){
            $resultarray[] = $r->count();
        }
        $aux = abs(count($resultarray) - 6);
        for($i = 1; $i <= $aux; $i++){
            $resultarray[] = 0;
        }
        $resultarray=array_reverse($resultarray);
        $resultarraystring='';
        foreach ($resultarray as $item){
            $resultarraystring=$resultarraystring."'".$item."'".",";
        }

        return view('dashboard.admin', compact('users','recursos','months','resultarraystring'));
    }

}

app/Http/Controllers/Dashboard/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\user\UpdateProfileDetailsRequest;
use App\Http\Requests\Dashboard\user\UpdateLoginDetailsRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $edit = true;
        $user = Auth::User();

        return view('dashboard.user.profile',compact('edit','user'));
    }

    /**
     * Update informações do usuario.
     *
     * @return \Illuminate\Http\Response
     */
    public function updateDetails(UpdateProfileDetailsRequest $request)
    {

        $user = Auth::User();
        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->phone = $request->phone;
        $user->email = $request->email;
        $user->save();

        return redirect()->back()->withSuccess('Perfil atualizado com sucesso!');
    }

    /**
     * Update informações de login.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateLoginDetails(UpdateLoginDetailsRequest $request)
    {
        $user = Auth::User();
        $user->password = $request->password;
        $user->save();

        return redirect()->back()->withSuccess('Perfil atualizado com sucesso!');
    }

}

resources/views/dashboard/settings/auth.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Configurações de auteticação')

@section('content_header')
    <h1>
        Autenticação e registro
        <small>configuração do sistema de autenticação e registro</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="javascript:;">Configurações</a></li>
        <li class="active">Autenticação e registro</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')
@can('Gerenciar configurações')
<div class="nav-tabs-custom">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li role="presentation" class="active">
            <a href="#auth" aria-controls="auth" role="tab" data-toggle="tab">
                <i class="fa fa-lock"></i>
                Autenticação
            </a>
        </li>
        <li role="presentation">
            <a href="#registration" aria-controls="registration" role="tab" data-toggle="tab">
                <i class="fa fa-user-plus"></i>
                Registro
            </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="auth">
            <div class="row">
                <div class="col-md-6">
                    @include('dashboard.settings.partials.auth')
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="registration">
            <div class="row">
                <div class="col-md-6">
                    @include('dashboard.settings.partials.registration')
                </div>
            </div>
        </div>
    </div>
</div>
@endcan
@stop

@section('js')
@stop

resources/views/dashboard/settings/general.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Configurações gerais')

@section('content_header')
    <h1>
        Configurações gerais
        <small>gerencie as configurações gerais do sistema</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li><a href="javascript:;">Configurações</a></li>
        <li class="active">Gerais</li>
    </ol>
@endsection

@section('content')
@include('partials.messages')

@can('Gerenciar configurações')
    <form action="{{route('dashboard.settings.general.update')}}" method="post">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Configurações gerais</div>
                    <div class="panel-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="app_name">Nome do site</label>
                                <input type="text" class="form-control" id="app_name"
                                       name="app_name" value="{{ setting('app_name')!=""?setting('app_name'):old('app_name') }}">
                            </div>
                            <div class="form-group">
                                <label for="app_name">Título do site</label>
                                <input type="text" class="form-control" id="title"
                                       name="title" value="{{ setting('title')!=""?setting('title'):old('title') }}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="terms">Termos e condições</label>
                                <textarea class="form-control" name="terms" id="terms" cols="30" rows="10">{{ setting('terms')!=""?setting('terms'):old('terms') }}</textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">Informações de contato</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="email">E-mail</label>
                            <input type="text" class="form-control" id="email"
                                   name="email" value="{{ setting('email')!=""?setting('email'):old('email') }}">
                        </div>
                        <div class="form-group">
                            <label for="telefone">Telefone</label>
                            <input type="text" class="form-control" id="telefone"
                                   name="telefone" value="{{ setting('telefone')!=""?setting('telefone'):old('telefone') }}">
                        </div>
                        <div class="form-group">
                            <label for="whatsapp">WhatsApp</label>
                            <input type="text" class="form-control" id="whatsapp"
                                   name="whatsapp" value="{{ setting('whatsapp')!=""?setting('whatsapp'):old('whatsapp') }}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">Contadores na Home</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="clientessatisfeitos">Clientes satisfeitos começar com:</label>
                            <input type="text" class="form-control" id="clientessatisfeitos"
                                   name="clientessatisfeitos" value="{{ setting('clientessatisfeitos')!=""?setting('clientessatisfeitos'):old('clientessatisfeitos') }}">
                        </div>
                        <div class="form-group">
                            <label for="recursos">Multas anuladas e convertidas começar com:</label>
                            <input type="text" class="form-control" id="recursos"
                                   name="recursos" value="{{ setting('recursos')!=""?setting('recursos'):old('recursos') }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-refresh"></i>
                    Atualizar configurações
                </button>
            </div>
        </div>
    </form>
@endcan
@stop

@section('js')
@stop