routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('checkout/notification', ['as' => 'checkout.notification','uses' => 'Frontend\CheckoutController@checkoutNotification']);


Route::get('/', ['as' => 'index','uses' => 'Frontend\IndexController@index']);
Route::get('/contato', ['as' => 'contato','uses' => 'Frontend\IndexController@contato']);

Route::get('login', ['as' => 'login','uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', ['as' => 'postlogin','uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'logout','uses' => 'Auth\LoginController@logout']);
Route::get('register', ['as'=>'register','uses'=>'Auth\RegisterController@showregister']);
Route::post('register', ['as'=>'postregister','uses' => 'Auth\RegisterController@register']);
if (setting('forgot_password')){
    Route::get('password/remind', ['as'=>'password.remind','uses'=>'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/remind', ['as'=>'send.password.remind','uses'=>'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset/{token}', ['as'=>'password.reset', 'uses'=>'Auth\ResetPasswordController@showResetForm']);
    Route::post('password/reset', ['as'=>'password.update','uses'=>'Auth\ResetPasswordController@reset']);
}

Route::group(['middleware' => 'auth'], function() {
    Route::get('recurso', ['as' => 'recurso.index','uses' => 'Frontend\RecursosController@create']);
    Route::post('recurso', ['as' => 'recurso.store','uses' => 'Frontend\RecursosController@store']);
    Route::get('recurso/{id}/pagar', ['as' => 'recurso.pagar','uses' => 'Frontend\RecursosController@pagar']);
    Route::post('recurso/{id}/pagar', ['as' => 'recurso.pagar.post','uses' => 'Frontend\RecursosController@pagarpost']);

    Route::get('minha-conta', ['as' => 'minhaconta.index','uses' => 'Frontend\MinhaContaController@index']);
    Route::get('minha-conta/recurso/{id}/editar', ['as' => 'minhaconta.recurso.edit','uses' => 'Frontend\MinhaContaController@edit']);
    Route::post('minha-conta/recurso/{id}/editar', ['as' => 'minhaconta.recurso.update','uses' => 'Frontend\MinhaContaController@update']);
    Route::post('minha-conta/recurso/{id}/editar/imagem', ['as' => 'minhaconta.recurso.update.image','uses' => 'Frontend\MinhaContaController@updateImage']);
    Route::get('minha-conta/configuracoes', ['as' => 'minhaconta.settings','uses' => 'Frontend\MinhaContaController@settings']);
    Route::post('minha-conta/configuracoes/editar', ['as' => 'minhaconta.settings.update.details','uses' => 'Frontend\MinhaContaController@settingsupdate']);
    Route::post('minha-conta/configuracoes/editar/senha', ['as' => 'minhaconta.settings.update.password','uses' => 'Frontend\MinhaContaController@settingsupdatepassword']);
    Route::get('minha-conta/recurso/{id}/download', ['as' => 'minhaconta.recurso.download','uses' => 'Frontend\MinhaContaController@download']);

    Route::get('checkout/success', ['as' => 'checkout.sucess','uses' => 'Frontend\RecursosController@checkoutSuccess']);
});



Route::group(['middleware' => ['auth','role:Administrador|Funcionário'],'prefix' => 'dashboard', 'as' => 'dashboard.'], function() {
    Route::get('/', ['as' => 'index','uses' => 'Dashboard\DashboardController@index']);

    Route::get('profile', ['as' => 'profile','uses' => 'Dashboard\ProfileController@index']);
    Route::post('profile/details/update', ['as' => 'profile.update.details','uses' => 'Dashboard\ProfileController@updateDetails']);
    Route::post('profile/login-details/update', ['as' => 'profile.update.login-details','uses' => 'Dashboard\ProfileController@updateLoginDetails']);

    Route::get('user', ['as' => 'user.list','uses' => 'Dashboard\UsersController@index']);
    Route::get('user/create', ['as' => 'user.create','uses' => 'Dashboard\UsersController@create']);
    Route::post('user/create', ['as' => 'user.store','uses' => 'Dashboard\UsersController@store']);
    Route::get('user/{user_id}/edit', ['as' => 'user.edit','uses' => 'Dashboard\UsersController@edit']);
    Route::post('user/{user_id}/update/details', ['as' => 'user.update.details','uses' => 'Dashboard\UsersController@updateDetails']);
    Route::post('user/{user_id}/update/login-details', ['as' => 'user.update.login-details','uses' => 'Dashboard\UsersController@updateLoginDetails']);      //----------testar
    Route::post('user/{user_id}/update/role', ['as' => 'user.update.role','uses' => 'Dashboard\UsersController@updateRole']);
    Route::post('user/{user_id}/update/permissions', ['as' => 'user.update.permission','uses' => 'Dashboard\UsersController@updatePermissions']);
    Route::delete('user/{user_id}/delete', ['as' => 'user.delete','uses' => 'Dashboard\UsersController@destroy']);

    Route::get('arquivo/download/{id}', ['as' => 'arquivo.download','uses' => 'Dashboard\ArquivosController@download']);

    Route::get('recurso', ['as' => 'recurso.list','uses' => 'Dashboard\RecursosController@index']);
    Route::get('recurso/{recurso_id}/edit', ['as' => 'recurso.edit','uses' => 'Dashboard\RecursosController@edit']);
    Route::post('recurso/{recurso_id}/update', ['as' => 'recurso.update','uses' => 'Dashboard\RecursosController@update']);
    Route::post('recurso/{recurso_id}/update/status', ['as' => 'recurso.update.recursofile','uses' => 'Dashboard\RecursosController@updateRecursoFile']);
    Route::post('recurso/{recurso_id}/update/pagamento', ['as' => 'recurso.update.pagamento','uses' => 'Dashboard\RecursosController@updatePagamento']);
    Route::get('recurso/{recurso_id}/view', ['as' => 'recurso.show','uses' => 'Dashboard\RecursosController@show']);
    Route::delete('recurso/{recurso_id}/delete', ['as' => 'recurso.delete','uses' => 'Dashboard\RecursosController@destroy']);

    Route::get('categoria', ['as' => 'categoria.list','uses' => 'Dashboard\CategoriasController@index']);
    Route::get('categoria/create', ['as' => 'categoria.create','uses' => 'Dashboard\CategoriasController@create']);
    Route::post('categoria/store', ['as' => 'categoria.store','uses' => 'Dashboard\CategoriasController@store']);
    Route::get('categoria/{id}/edit', ['as' => 'categoria.edit','uses' => 'Dashboard\CategoriasController@edit']);
    Route::post('categoria/{id}/update', ['as' => 'categoria.update','uses' => 'Dashboard\CategoriasController@update']);
    Route::delete('categoria/{id}/delete', ['as' => 'categoria.destroy','uses' => 'Dashboard\CategoriasController@destroy']);


    Route::get('infracao', ['as' => 'tipomulta.list','uses' => 'Dashboard\TipoMultasController@index']);
    Route::get('infracao/create', ['as' => 'tipomulta.create','uses' => 'Dashboard\TipoMultasController@create']);
    Route::post('infracao/store', ['as' => 'tipomulta.store','uses' => 'Dashboard\TipoMultasController@store']);
    Route::get('infracao/{id}/edit', ['as' => 'tipomulta.edit','uses' => 'Dashboard\TipoMultasController@edit']);
    Route::post('infracao/{id}/update', ['as' => 'tipomulta.update','uses' => 'Dashboard\TipoMultasController@update']);
    Route::delete('infracao/{id}/delete', ['as' => 'tipomulta.destroy','uses' => 'Dashboard\TipoMultasController@destroy']);


    Route::get('role', ['as' => 'role.index','uses' => 'Dashboard\RolesController@index']);
    Route::get('role/create', ['as' => 'role.create','uses' => 'Dashboard\RolesController@create']);
    Route::post('role/store', ['as' => 'role.store','uses' => 'Dashboard\RolesController@store']);
    Route::get('role/{role_id}/edit', ['as' => 'role.edit','uses' => 'Dashboard\RolesController@edit']);
    Route::post('role/{role_id}/update', ['as' => 'role.update','uses' => 'Dashboard\RolesController@update']);
    Route::delete('role/{role_id}/delete', ['as' => 'role.delete','uses' => 'Dashboard\RolesController@destroy']);

    Route::get('permission', ['as' => 'permission.index','uses' => 'Dashboard\PermissionsController@index']);
    Route::get('permission/create', ['as' => 'permission.create','uses' => 'Dashboard\PermissionsController@create']);
    Route::post('permission/store', ['as' => 'permission.store','uses' => 'Dashboard\PermissionsController@store']);
    Route::get('permission/{permission_id}/edit', ['as' => 'permission.edit','uses' => 'Dashboard\PermissionsController@edit']);
    Route::post('permission/{permission_id}/update', ['as' => 'permission.update','uses' => 'Dashboard\PermissionsController@update']);
    Route::delete('permission/{permission_id}/delete', ['as' => 'permission.destroy','uses' => 'Dashboard\PermissionsController@destroy']);

    Route::get('settings', ['as' => 'settings.general','uses' => 'Dashboard\SettingsController@general']);
    Route::post('settings/general', ['as' => 'settings.general.update','uses' => 'Dashboard\SettingsController@updategeneral']);
    Route::get('settings/auth', ['as' => 'settings.auth','uses' => 'Dashboard\SettingsController@auth']);
    Route::post('settings/auth', ['as' => 'settings.auth.update','uses' => 'Dashboard\SettingsController@updateauth']);
});

app/Http/Controllers/Dashboard/ArquivosController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Arquivo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class ArquivosController extends Controller
{
    public function download($id)
    {
        $arquivo = Arquivo::find($id);

        return Storage::download($arquivo->path);
    }

    public function delete($id)
    {
        $arquivo = Arquivo::find($id);
        $recurso_id = $arquivo->recurso_id;

        Storage::delete($arquivo->path);

        return redirect()->route('dashboard.recurso.edit',$recurso_id)->withSuccess('Arquivo excluido com sucesso!');
    }
}

app/Http/Controllers/Dashboard/CategoriasController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\Categoria\CreateCategoriaRequest;
use App\Http\Requests\Dashboard\Categoria\UpdateCategoriaRequest;
use App\Models\Categoria;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;

class CategoriasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Auth::user()->can('Visualizar categoria')){
            return redirect()->back();
        }
        $peer_page = 15;
        $search = Input::get('search');
        $categorias = Categoria::Query();
        if ($search <> "") {
            $categorias->where(function ($q) use ($search) {
                $q->where('nome', "like", "%{$search}%");
            });
        }
        $categorias = $categorias->paginate($peer_page);
        if ($search) {
            $categorias->appends(['search' => $search]);
        }

        return view('dashboard.categoria.list', compact('categorias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!Auth::user()->can('Criar categoria')){
            return redirect()->back();
        }

        return view('dashboard.categoria.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoriaRequest $request)
    {
        if(!Auth::user()->can('Criar categoria')){
            return redirect()->route('dashboard.categoria.list')->withErrors('Você não esta autorizado para executar esta ação.');
        }

        $categoria = new Categoria();
        $categoria->nome = $request->nome;
        $categoria->preco = $request->preco;
        $categoria->save();

        return redirect()->route('dashboard.categoria.list')->withSuccess('Categoria criada com sucesso!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $$tipomulta_id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!Auth::user()->can('Editar categoria')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }
        $edit = true;
        $categoria = Categoria::find($id);

        return view('dashboard.categoria.edit',compact('edit', 'categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoriaRequest $request, $id)
    {
        if(!Auth::user()->can('Editar categoria')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }

        $categoria = Categoria::find($id);
        $categoria->nome = $request->nome;
        $categoria->preco = $request->preco;
        $categoria->save();

        return redirect()->back()->withSuccess('Categoria atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!Auth::user()->can('Excluir categoria')){
            return redirect()->back()->withErrors('Você não esta autorizado para executar esta ação.');
        }
        $categoria = Categoria::find($id);
        $categoria->delete();

        return redirect()->route('dashboard.categoria.list')->withSuccess('Categoria excluída com sucesso!');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Recurso;
use App\Models\User;
use Carbon\Carbon;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $recursos = Recurso::all();

        $monthsarray[] = date('m/Y');
        for ($i = 1; $i < 6; $i++) {
            $monthsarray[] = date('m/Y', strtotime("-$i month"));
        }
        $months='';
        foreach ($monthsarray as $m){
            $months="'".$m."'".",".$months;
        }

        $result = Recurso::select('id', 'created_at')
            ->where("created_at",">", Carbon::now()->subMonths(6))
            ->get()
            ->groupBy(function($date) {
                return Carbon::parse($date->created_at)->format('m');
            });
        $resultarray = [];
        foreach ($result as $r){
            $resultarray[] = $r->count();
        }
        $aux = abs(count($resultarray) - 6);
        for($i = 1; $i <= $aux; $i++){
            $resultarray[] = 0;
        }
        $resultarray=array_reverse($resultarray);
        $resultarraystring='';
        foreach ($resultarray as $item){
            $resultarraystring=$resultarraystring."'".$item."'".",";
        }

        return view('dashboard.admin', compact('users','recursos','months','resultarraystring'));
    }

}

app/Http/Controllers/Dashboard/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\user\UpdateProfileDetailsRequest;
use App\Http\Requests\Dashboard\user\UpdateLoginDetailsRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $edit = true;
        $user = Auth::User();

        return view('dashboard.user.profile',compact('edit','user'));
    }

    /**
     * Update informações do usuario.
     *
     * @return \Illuminate\Http\Response
     */
    public function updateDetails(UpdateProfileDetailsRequest $request)
    {

        $user = Auth::User();
        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->phone = $request->phone;
        $user->email = $request->email;
        $user->save();

        return redirect()->back()->withSuccess('Perfil atualizado com sucesso!');
    }

    /**
     * Update informações de login.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateLoginDetails(UpdateLoginDetailsRequest $request)
    {
        $user = Auth::User();
        $user->password = $request->password;
        $user->save();

        return redirect()->back()->withSuccess('Perfil atualizado com sucesso!');
    }

}

resources/views/dashboard/role/add.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Adicionar papel')

@section('content_header')
    <h1>
        Criar novo papel
        <small>Detalhes do papel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li>Papéis</li>
        <li class="active">Criar</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')
@can('Criar papéis')
    <form action="{{route('dashboard.role.store')}}" method="post">
    @csrf
    <div class="row">
        <div class="col-md-12">
            @include('dashboard.role.partials.details', ['edit' => false])
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary">
                <i class="fa fa-save"></i>
                Criar papel
            </button>
        </div>
    </div>
    </form>
@endcan
@stop

resources/views/dashboard/role/edit.blade.php
@extends('dashboard.layouts.master')

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
@endsection

@section('page-title', 'Editar papel')

@section('content_header')
    <h1>
        {{ $role->name }}
        <small>editar detalhes do papel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li>Papéis</li>
        <li class="active">Editar</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')

<div class="nav-tabs-custom">
    <!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#details" aria-controls="details" role="tab" data-toggle="tab">
            <i class="glyphicon glyphicon-th"></i>
            Detalhes
        </a>
    </li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="details">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                @can('Editar papéis')
                    <form action="{{route('dashboard.role.update',$role->id)}}" method="post">
                    @csrf
                    @include('dashboard.role.partials.details')
                    </form>
                @endcan
            </div>
        </div>
    </div>
</div>
</div>

@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
@stop

resources/views/dashboard/role/list.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Papéis')
@section('content_header')
<h1>
    Papéis
</h1>
<ol class="breadcrumb">
    <li><a href="{{ route('dashboard.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">Papéis</li>
</ol>
@endsection
@section('content')
@include('partials.messages')

<div class="row tab-search">
    <div class="col-md-2 col-xs-2">
        @can('Criar papéis')
        <a href="{{ route('dashboard.role.create') }}" class="btn btn-success" id="add-user">
            <i class="glyphicon glyphicon-plus"></i>
            Adicionar papel
        </a>
        @endcan
    </div>
    <div class="col-md-5 col-xs-3"></div>
    <form method="GET" action="" accept-charset="UTF-8" id="link-form">
        <div class="col-md-3 col-xs-4">
            <div class="input-group custom-search-form">
                <input type="text" class="form-control" name="search" value="{{ app('request')->input('search') }}" placeholder="Procure por papéis...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" id="search-users-btn">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                    @if (app('request')->input('search') != '')
                        <a href="{{ route('dashboard.role.index') }}" class="btn btn-danger" type="button" >
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    @endif
                </span>
            </div>
        </div>
    </form>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Lista de papéis cadastrados</h3>
            </div>
            <div class="box-body table-responsive no-padding">
                <div id="users-table-wrapper">
                    <table class="table table-hover table-striped">
                        <tbody>
                            <tr>
                                <th>Nome</th>
                                <th class="text-center">Ações</th>
                            </tr>
                            @if (count($roles))
                            @foreach ($roles as $role)
                            <tr>
                                <td>{{ $role->name }}</td>
                                <td class="text-center">
                                    @can('Editar papéis')
                                    <a href="{{ route('dashboard.role.edit', $role->id) }}" class="btn btn-primary btn-circle edit" title="Editar papel"
                                        data-toggle="tooltip" data-placement="top">
                                        <i class="glyphicon glyphicon-edit"></i>
                                    </a>
                                    @endcan
                                    @can('Excluir papéis')
                                    <a href="{{ route('dashboard.role.delete', $role->id) }}" class="btn btn-danger btn-circle" title="Excluir papel"
                                        data-toggle="tooltip"
                                        data-placement="top"
                                        data-method="DELETE"
                                        data-confirm-title="Por favor confirme"
                                        data-confirm-text="Tem certeza que deseja excluir esse papel?"
                                        data-confirm-delete="Sim">
                                        <i class="glyphicon glyphicon-trash"></i>
                                    </a>
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                            @else
                            <tr>
                                <td colspan="6" class="text-center"><em>Registros não foram encontrados</em></td>
                            </tr>
                            @endif
                        </tbody>
                    </table>
                    <div class="text-center">
                        {{ $roles->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('js')
    <script src="{{ asset('js/delete.handler.js') }}"></script>
@stop